name: Exios Admin Frontend CI
on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '16.13.1'
      - run: npm install
      - run: npm start